spring:
  profiles:
    active: local
    group:
      local: local,common
      blue: blue,common
      green: green,common

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server
---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 3.37.122.209 # 탄력적 IP

serverName: blue_server
---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 3.37.122.209 # 탄력적 IP

serverName: green_server
---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/its?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: zpzzgjdg@$^1

  batch:
    jdbc:
      initialize-schema: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cache:
    type: redis
    redis:
      cache-null-values: true

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    tempSecret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb




  # spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  # spring.datasource.url=jdbc:mysql://127.0.0.1:3306/its?serverTimezone=UTC&characterEncoding=UTF-8
  # spring.datasource.username=root
  # spring.datasource.password=zpzzgjdg@$^1

  # spring.jpa.show-sql=true
  # spring.jpa.hibernate.ddl-auto=create
  # spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
  # spring.jpa.properties.hibernate.format_sql=true
  # spring.jpa.properties.hibernate.highlight_sql=true
  # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

  # spring.jwt.tempSecret=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  # server.port=8080
