package mediaproject.its.domain.entity.PostCategories;

// 기술 스택
public enum TechStackType {
    JAVASCRIPT, TYPESCRIPT, REACT, VUE, SVELTE, NEXTJS, NODEJS, JAVA, SPRING, GO, NESTJS, KOTLIN, EXPRESS, MYSQL,
    MONGODB, PYTHON, DJANGO, PHP, GRAPHQL, FIREBASE, FLUTTER, SWIFT, REACTNATIVE, UNIRY, AWS, KUBERNETES, DOCKER,
    GIT, FIGMA, ZEPLIN, JEST,;
}
